name: Build and run SystemTest for Backend
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Upgrade python-pip
        run: pip install --upgrade pip
      - name: Install Python Dependencies
        run: 
          pip install requests
          pip install flask
          pip install psutil
      - name: Generate Datebase
        run: python Scripts/generate_new_database.py
      - name: Run BackendSystemTests
        run: python BackendSystemTests --linux --loglevel DEBUG
